default_stages: [pre-commit]
default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        exclude: "{{ cookiecutter.repo_name }}/environment.yml"

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.4.1
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: "{{ cookiecutter.repo_name }}/environment.yml"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.0
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/f-koehler/conda-hooks
    rev: 0.5.0
    hooks:
      - id: conda-env-store
