name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pip:
    - -e .
  - setuptools
  - wheel
  - click
  - python={{ cookiecutter.python_version }}
  - ipykernel
  - snakemake
  - poetry
