name: {{cookiecutter.repo_name}}
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
  - setuptools
  - wheel
  - click
  - flake8
  - flake8-isort
  - python-dotenv>=0.5.1
  - python=3
  - ipykernel
