# prettier-ignore
name: {{ cookiecutter.repo_name }}  # yamllint disable-line
channels:
  - conda-forge
  - bioconda
dependencies:
  - git
  - ipykernel
  - pip
  - poetry
  - pre-commit
  # prettier-ignore
  - python={{ cookiecutter.python_version }}  # yamllint disable-line
  - snakemake
  - pip:
      - -e .
