name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - bioconda
dependencies:
  - ipykernel
  - pip
  - pip:
    - -e .
  - poetry
  - python={{ cookiecutter.python_version }}
  - snakemake
