name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pip:
    - -e .
  - setuptools
  - wheel
  - click
  - flake8
  - flake8-isort>=4
  - python-dotenv>=0.5.1
  - python={{ cookiecutter.python_version }}
  - ipykernel
  - snakemake
