PROJECT_NAME = "{{ cookiecutter.repo_name }}"
CODE_DIR = "{{ cookiecutter.python_module_name }}"
PYTHON_VERSION = "{{ cookiecutter.python_version }}"

NOTEBOOKS_DIR = "notebooks"

DATA_DIR = "data"
DATA_RAW_DIR = f"{DATA_DIR}/raw"
DATA_INTERIM_DIR = f"{DATA_DIR}/interim"
DATA_PROCESSED_DIR = f"{DATA_DIR}/processed"

# 0. conda/mamba environment -----------------------------------------------------------
rule create_environment:
    run:
        shell(
            f"mamba create -n {PROJECT_NAME} -c conda-forge python={PYTHON_VERSION} -y"
        )
        shell(f"mamba env update -n {PROJECT_NAME} --file environment.yml")


rule register_ipykernel:
    shell:
        f"python -m ipykernel install --user --name {PROJECT_NAME} --display-name "
        f'"Python ({PROJECT_NAME})"'
