from pathlib import Path

PROJECT_NAME = "{{ cookiecutter.repo_name }}"
CODE_DIR = "{{ cookiecutter.python_module_name }}"
PYTHON_VERSION = "{{ cookiecutter.python_version }}"

NOTEBOOKS_DIR = Path("notebooks")

DATA_DIR = Path("data")
DATA_RAW_DIR = DATA_DIR / "raw"
DATA_INTERIM_DIR = DATA_DIR / "interim"
DATA_PROCESSED_DIR = DATA_DIR / "processed"
