from os import path

PROJECT_NAME = "{{ cookiecutter.repo_name }}"
CODE_DIR = "{{ cookiecutter.python_module_name }}"
PYTHON_VERSION = "{{ cookiecutter.python_version }}"

NOTEBOOKS_DIR = "notebooks"

DATA_DIR = "data"
DATA_RAW_DIR = path.join(DATA_DIR, "raw")
DATA_INTERIM_DIR = path.join(DATA_DIR, "interim")
DATA_PROCESSED_DIR = path.join(DATA_DIR, "processed")

# 0. conda/mamba environment -----------------------------------------------------------
rule create_environment:
    shell:
        "mamba env create -f environment.yml"


rule register_ipykernel:
    shell:
        "python -m ipykernel install --user --name {PROJECT_NAME} --display-name"
        " 'Python ({PROJECT_NAME})'"
